#!/bin/sh
INCREMENT="$2"
display="${3:-eDP-1}"

brightness="$(xrandr --verbose | awk '/Brightness/ {print $2; exit}')"

case "$1" in
	"+")
		new_brightness=$(echo "$brightness + $INCREMENT" | bc)
		xrandr --output $display --brightness $new_brightness
		;;
	"-")
		new_brightness=$(echo "$brightness - $INCREMENT" | bc)
		xrandr --output $display --brightness $new_brightness
		;;
	*)
		echo $brightness
		;;
esac

